const HOME_ROUTE = "/";
const JAVASCRIPT_ROUTE = "/javascript";
const JAVASCRIPT_ADD_ROUTE = "/javascript/add";

const JAVASCRIPT_LIST_ACTION = "JAVASCRIPT_LIST_ACTION";
const JAVASCRIPT_ADD_ACTION = "JAVASCRIPT_ADD_ACTION";
const JAVASCRIPT_REMOVE_ACTION = "JAVASCRIPT_REMOVE_ACTION";
const JAVASCRIPT_CHANGE_STATUS_ACTION = "JAVASCRIPT_CHANGE_STATUS_ACTION";

export {
  HOME_ROUTE,
  JAVASCRIPT_ROUTE,
  JAVASCRIPT_ADD_ROUTE,
  JAVASCRIPT_LIST_ACTION,
  JAVASCRIPT_ADD_ACTION,
  JAVASCRIPT_REMOVE_ACTION,
  JAVASCRIPT_CHANGE_STATUS_ACTION
};
