const HOME_ROUTE = "/";
const JAVASCRIPT_ROUTE = "/javascript";
const JAVASCRIPT_ADD_ROUTE = "/javascript/add";

const JAVASCRIPT_LIST_ACTION = "JAVASCRIPT_LIST_ACTION";
const JAVASCRIPT_ADD_ACTION = "JAVASCRIPT_ADD_ACTION";

export {
  HOME_ROUTE,
  JAVASCRIPT_ROUTE,
  JAVASCRIPT_ADD_ROUTE,
  JAVASCRIPT_LIST_ACTION,
  JAVASCRIPT_ADD_ACTION
};
